### ISSUE TITLE
submission todo

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/PhenograssReplication#6]
### Writing

- [x] finish discussion
- [x] finalize map
- [x] abstract
- [x] list our software cites
- [x] #7 
- [x] cite supplement tables in text
- [x] acknowledgments
- [x] correct R2 everywhere
- [x] bold text in results table
- [x] include CV result in result table

### Supplement

- [x] table of individual site info/ R2 values, probably rmse too
- [x] marker whether a site was included in original paper
- [ ] giant figure of fitted timeseries

### Submission logistics

- [x] collect references
- [x] do latex tables
- [x] get into overleaf w/ biogeosciences template
- [x] upload repo + GrasslandModels package to zenodo
- [x] repo readme

**Comment by sdtaylor** [comment]
BG instructions https://www.biogeosciences.net/for_authors/manuscript_preparation.html

Also seems like they accept markdown stuff

In general: line numbers, numbered pages, specific code/data statement, author contribs

Nothing about having figs/tables at the end. But it does say to include separate files for them. 

supplement for BG is saved for things like really large videos. extra tables/figs go in the appendix

**Comment by sdtaylor** [comment]
cover letter. biogeosciences states just a few sentences. 


The PhenoGrass model is a productivity model parameterized from near-surface cameras. We re-evaluated the model using 5 additional years of data from 77 new sites which have come available since the original study. We expanded on the the original analysis by evaluating at several scale combinations and new vegetation types to determine where the model was most suited, and where it could either be improved or substituted with a more appropriate model. Results from this study will be used in tools to inform land managers of future changes in grassland productivity due to climate change.

**Comment by sdtaylor** [comment]
command to zip everything minus git stuff

`zip -r -0 --exclude=*.git* phenograss_paper.zip PhenograssReplication/ GrasslandModels/`

**Comment by sdtaylor** [comment]
Interpretive summary for ARIS 115 form

Grasslands provide a large amount of ecosystem services globally and forecasting grassland productivity in the coming decades will provide valuable information to land managers. Forecasts of grassland productivity have a multitude of components, ranging from precipitation measurements to estimates of above ground biomass, and numerical models of grassland processes. Each of these components needs independent validation to find its strengths and weaknesses, ensuring the resulting forecasts are sound. We evaluated a grass forecast model using nearly 500 years of grassland camera data and found the locations which is was most suitable, as well as locations where it did not perform well. Long-term grassland forecasts for the suitable locations can be made immediately with the current model, while other areas will need further model development.

**Comment by sdtaylor** [comment]
done https://doi.org/10.5194/bg-18-2213-2021
